### ISSUE TITLE
nsh link to GitHub is pointing to resea

### ISSUE THREAD

**Issue by unpause** [seiyanuta/seiya.me#1]
Hello,

the link to the GitHub on the nsh page is pointing to the resea GitHub repository instead of the nsh repository.

See here:[
https://github.com/seiyanuta/seiya.me/blob/592abdd6c77eec6815b64c725d809a88b86730e0/nsh/index.html#L24](
https://github.com/seiyanuta/seiya.me/blob/592abdd6c77eec6815b64c725d809a88b86730e0/nsh/index.html#L24)

**Comment by seiyanuta** [comment]
Thank you for pointing that out! The fix will be applied soon.
